name: 'XNow ID Server 4'


trigger: none

pr: none

pool:
  vmImage: "windows-latest"

steps:
  - task: Bash@3
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/build.sh'
  
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(System.DefaultWorkingDirectory)/src/**/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '4645071d-da7d-471c-9447-d2607af2bc8f/ef9cf9bb-3a1f-4941-b4ef-44cc6a2cd8a7'